name: ADGuardHome 反馈
description: 提交 ADGuardHome 相关问题或反馈
title: "[ADGuardHome] "
labels: ["adguardhome", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您花时间反馈 ADGuardHome 的问题！请尽量详细填写以下内容，便于开发者定位和解决问题。

  - type: input
    id: contact
    attributes:
      label: 联系方式
      description: 如果需要进一步信息，如何联系您？（可选）
      placeholder: 例如：email@example.com
    validations:
      required: false

  - type: textarea
    id: issue-description
    attributes:
      label: 故障现象
      description: 请详细描述您遇到的问题或异常表现。包含现象、影响、期望结果等。
      placeholder: 例如：DNS 解析失败，网页无法加载等
    validations:
      required: true

  - type: textarea
    id: cause
    attributes:
      label: 已知原因（如有）
      description: 如果您认为已知故障原因，请在此描述。没有可留空。
      placeholder: 例如：某个规则冲突，软件更新后出现等
    validations:
      required: false

  - type: textarea
    id: reproduce
    attributes:
      label: 浮现（复现）方法
      description: 描述如何触发此问题。若无法明确复现方法，请简要说明，或选择下方“仅提问”。
      placeholder: 例如：1. 启动 ADGuardHome 2. 访问 example.com 3. 页面报错
    validations:
      required: false

  - type: checkboxes
    id: only-question
    attributes:
      label: 复现方法不明确？
      description: 如果您无法明确复现方法，仅作为问题咨询，请勾选此项
      options:
        - label: 复现方法不明确，仅提问（Question）
          required: false

  - type: textarea
    id: logs
    attributes:
      label: 相关日志
      description: 请粘贴与问题相关的 ADGuardHome 日志（建议去除敏感信息）。内容将自动格式化，无需添加反引号。
      render: shell
    validations:
      required: false

  - type: dropdown
    id: version
    attributes:
      label: ADGuardHome 版本
      description: 您当前使用的 ADGuardHome 版本号
      options:
        - "未知"
        - "v0.107.x 稳定版"
        - "v0.107.x 测试版"
        - "自编译/其他"
      default: 0
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: 部署环境
      description: 您运行 ADGuardHome 的环境，如系统/平台/设备型号
      placeholder: 例如：Windows 10、OpenWrt、树莓派 4B 等
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: 行为准则
      description: 提交议题即表示您同意遵守本项目的 [行为准则](https://github.com/AdguardTeam/AdGuardHome/blob/master/.github/CODE_OF_CONDUCT.md)
      options:
        - label: 我同意遵守本项目的行为准则
          required: true