blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/orgs/community/discussions
    about: 请在这里提问或解答一般性问题。
  - name: ADGuard 官方支持
    url: https://adguard.com/
    about: 商业技术支持或其他官方服务请前往官网。